AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  BucketName:
    Type: String
    Description: The Name of the the S3 Bucket.
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref BucketName
Outputs:
  BucketARN:
    Value: !GetAtt "S3Bucket.Arn"
    Description: S3 Bucket ARN
    Export:
      Name: !Sub "${AWS::StackName}-BucketARN"
  BucketDomainName:
    Value: !GetAtt "S3Bucket.DomainName"
    Description: S3 Bucket DomainName
    Export:
      Name: !Sub "${AWS::StackName}-BucketDomainName"
  BucketRegionalDomainName:
    Value: !GetAtt "S3Bucket.RegionalDomainName"
    Description: S3 Bucket RegionalDomainName
    Export:
      Name: !Sub "${AWS::StackName}-BucketRegionalDomainName"
  BucketWebsiteUrl:
    Value: !GetAtt "S3Bucket.WebsiteURL"
    Description: S3 Bucket WebsiteURL
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteURL"
